# Read the Docs configuration file
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  output_base: $READTHEDOCS_OUTPUT  # <-- Add this line

sphinx:
  configuration: docs/source/conf.py
  builder: html
