version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

sphinx:
  configuration: conf.py
  fail_on_warning: false  # Change to false temporarily while debugging

python:
  install:
    - requirements: docs/requirements.txt